# Generated by Django 2.2.4 on 2019-10-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('cpf', models.CharField(help_text='Somente Números', max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário Ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário Funcionário?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Acesso de SuperUsuário?')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Último Login')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Última edição')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupo de permissão do usuário.', related_name='user_groups', related_query_name='user', to='auth.Group', verbose_name='Grupos de Usuário')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissões do usuário.', related_name='user_permissions', related_query_name='user', to='auth.Permission', verbose_name='Permissões do Usuário')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
